name: Publish Docker image

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  workflow_call:
  workflow_dispatch:

# avoid race conditions when multiple pushes happen in a short time
# e.g. by merging multiple PRs
# can otherwise result "older" commits being pushed as the :main image tag
concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build container image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ghcr.io/strayer/pdf-to-image-web-converter:latest
